import { zonedDateToUtc, zonedTimeParts } from "./timezone.js";

export interface Slot {
  start: Date;
  end: Date;
}

export interface BusyPeriod {
  start: Date;
  end: Date;
}

export interface AvailabilityRules {
  timezone: string;
  workdayStart: string; // "HH:MM" -- Monday-Friday start, and Saturday's own start (reused, never a separate value -- see workdayBoundsForLocalDate)
  workdayEnd: string; // "HH:MM" -- Monday-Friday end only
  // Fase 7F -- Baluarte Capital's real commercial hours: Saturday closes earlier than the rest of
  // the week (Saturday keeps workdayStart as its own start), and Sunday is closed entirely by
  // default. See workdayBoundsForLocalDate's own doc comment for the exact per-day rule.
  saturdayWorkdayEnd: string; // "HH:MM"
  sundayBookingEnabled: boolean;
  minNoticeHours: number;
  maxDaysAhead: number;
  maxSlots: number;
}

/**
 * Fase 7F -- the single source of truth for "what hours does this LOCAL calendar day operate
 * under", given `rules`. Returns `null` when the day is fully closed (Sunday, unless explicitly
 * enabled) -- callers must never generate or accept a slot for a `null` day.
 *
 * `y`/`m`/`d` must already be the LOCAL (rules.timezone) calendar date -- this function itself
 * does no timezone conversion, it only decides business hours from a day-of-week already resolved
 * correctly by the caller (see zonedTimeParts). Day-of-week is derived via `Date.UTC(y, m-1,
 * d).getUTCDay()` -- safe and correct here specifically because y/m/d are already a LOCAL
 * calendar date, not a UTC instant; this is pure calendar arithmetic (which weekday is
 * "2026-09-06"), never a timezone-dependent instant comparison.
 *
 * Monday-Friday: `workdayStart` -> `workdayEnd` (today's existing, unchanged hours).
 * Saturday: `workdayStart` (reused, never a separate "Saturday start" config -- Fase 7F spec: "No
 * asumir una hora de inicio nueva... reutilizarla para sábado") -> `saturdayWorkdayEnd`.
 * Sunday: closed (`null`) unless `sundayBookingEnabled` is explicitly true, in which case it
 * falls back to the SAME Monday-Friday hours (never a separate, invented "Sunday schedule" --
 * there is no commercial requirement for one, and this flag exists only as an explicit off-switch
 * per the spec, not as the seed of a whole new schedule shape).
 */
export function workdayBoundsForLocalDate(
  year: number, month: number, day: number, rules: AvailabilityRules,
): { startH: number; startM: number; endH: number; endM: number } | null {
  const dayOfWeek = new Date(Date.UTC(year, month - 1, day)).getUTCDay(); // 0=Sunday, 6=Saturday
  const [startH, startM] = rules.workdayStart.split(":").map(Number);
  if (dayOfWeek === 0) {
    if (!rules.sundayBookingEnabled) return null;
    const [endH, endM] = rules.workdayEnd.split(":").map(Number);
    return { startH, startM, endH, endM };
  }
  if (dayOfWeek === 6) {
    const [endH, endM] = rules.saturdayWorkdayEnd.split(":").map(Number);
    return { startH, startM, endH, endM };
  }
  const [endH, endM] = rules.workdayEnd.split(":").map(Number);
  return { startH, startM, endH, endM };
}

/**
 * Fase 7F -- the ONE place that decides whether an EXACT, already-chosen start/end (as opposed to
 * a candidate generated by enumerateWorkdaySlots below) falls inside business hours. Used by
 * AppointmentService.completeBooking to protect a "direct" booking call (one that names an exact
 * time rather than picking from an offered slot) from ever landing outside business hours or on a
 * closed day -- the same rule the slot-generation path already enforces by construction, now also
 * enforced explicitly at the point of booking. Never confirms availability against Google
 * Calendar itself (that's CalendarProvider.isSlotAvailable's job) -- this is business-hours only.
 */
export function isWithinBusinessHours(start: Date, end: Date, rules: AvailabilityRules): boolean {
  const startParts = zonedTimeParts(start, rules.timezone);
  const bounds = workdayBoundsForLocalDate(startParts.year, startParts.month, startParts.day, rules);
  if (!bounds) return false;
  const dayStart = zonedDateToUtc(startParts.year, startParts.month, startParts.day, bounds.startH, bounds.startM, rules.timezone);
  const dayEnd = zonedDateToUtc(startParts.year, startParts.month, startParts.day, bounds.endH, bounds.endM, rules.timezone);
  return start.getTime() >= dayStart.getTime() && end.getTime() <= dayEnd.getTime();
}

export function clampAvailabilityWindow(
  from: Date,
  to: Date,
  rules: Pick<AvailabilityRules, "minNoticeHours" | "maxDaysAhead">,
  now: Date = new Date(),
): { from: Date; to: Date } {
  const minNoticeCutoff = new Date(now.getTime() + rules.minNoticeHours * 3_600_000);
  const maxHorizon = new Date(now.getTime() + rules.maxDaysAhead * 86_400_000);
  const effectiveFrom = new Date(Math.max(from.getTime(), minNoticeCutoff.getTime(), now.getTime()));
  const effectiveTo = new Date(Math.min(to.getTime(), maxHorizon.getTime()));
  return { from: effectiveFrom, to: effectiveTo };
}

export function computeAvailableSlots(
  from: Date,
  to: Date,
  durationMinutes: number,
  busy: BusyPeriod[],
  rules: AvailabilityRules,
  now: Date = new Date(),
): Slot[] {
  const { from: effectiveFrom, to: effectiveTo } = clampAvailabilityWindow(from, to, rules, now);
  if (effectiveFrom >= effectiveTo) return [];

  const candidates = enumerateWorkdaySlots(effectiveFrom, effectiveTo, durationMinutes, rules);
  const free = candidates.filter((slot) => !busy.some((b) => slot.start < b.end && slot.end > b.start));
  free.sort((a, b) => a.start.getTime() - b.start.getTime());
  return free.slice(0, rules.maxSlots);
}

function enumerateWorkdaySlots(from: Date, to: Date, durationMinutes: number, rules: AvailabilityRules): Slot[] {
  const fromParts = zonedTimeParts(from, rules.timezone);
  const baseDay = new Date(Date.UTC(fromParts.year, fromParts.month - 1, fromParts.day));
  const maxDays = rules.maxDaysAhead + 2; // safety buffer against off-by-one at the horizon edge
  const durationMs = durationMinutes * 60_000;
  const slots: Slot[] = [];

  for (let dayOffset = 0; dayOffset <= maxDays; dayOffset++) {
    const day = new Date(baseDay.getTime() + dayOffset * 86_400_000);
    const y = day.getUTCFullYear();
    const m = day.getUTCMonth() + 1;
    const d = day.getUTCDate();
    // Fase 7F -- per-day bounds (Monday-Friday vs Saturday vs closed Sunday), never a single
    // fixed start/end reused blindly across every day of the week. A closed day (null bounds)
    // simply contributes zero slots -- never falls back to the weekday hours by accident.
    const bounds = workdayBoundsForLocalDate(y, m, d, rules);
    if (!bounds) continue;
    const dayStart = zonedDateToUtc(y, m, d, bounds.startH, bounds.startM, rules.timezone);
    const dayEnd = zonedDateToUtc(y, m, d, bounds.endH, bounds.endM, rules.timezone);
    if (dayStart.getTime() > to.getTime()) break;
    for (let t = dayStart.getTime(); t + durationMs <= dayEnd.getTime(); t += durationMs) {
      const slotStart = new Date(t);
      const slotEnd = new Date(t + durationMs);
      if (slotStart.getTime() >= from.getTime() && slotEnd.getTime() <= to.getTime()) {
        slots.push({ start: slotStart, end: slotEnd });
      }
    }
  }
  return slots;
}
