import type { FiscalCalculatorNoteInput } from "./fiscal-calculator-lead-note.js";
import type { FiscalScoreClass } from "./fiscal-lead-score.js";

/**
 * Fase 6F / 6F.1 -- pure mapping from a fiscal calculator submission (the SAME structured payload
 * already used by formatFiscalCalculatorNote for leads.notes -- reused here, not redefined, per
 * this task's "buscar si ya existe un campo equivalente antes de crear uno nuevo" instruction) to
 * a flat HubSpot Contact `properties` object.
 *
 * Deliberately pure and HTTP-free: no fetch, no HubSpotCRMProvider import, no Lead/domain
 * entities beyond the types above. This is the ONE place that decides exactly which fiscal
 * figures leave Lead Engine and land in HubSpot, so its output is easy to assert on in isolation
 * -- same rationale as formatFiscalCalculatorNote's own doc comment. It performs NO calculation of
 * its own beyond a plain sum of the 4 deduction inputs (bc_fiscal_personal_deductions, kept as a
 * convenience total alongside -- never instead of -- the 4 individual deduction properties added
 * in Fase 6F.1) -- every other number is transported verbatim from the calculator engine's own
 * output (see the Fase 6F.1 report, item 6).
 *
 * Identification fields (firstname/lastname/email/phone) and native HubSpot fields (city/state)
 * are DELIBERATELY NOT built here -- those map onto HubSpot's own default/standard contact
 * properties (already exist in every portal, reused rather than shadowed with a bc_fiscal_*
 * duplicate -- see the Fase 6F report, item 5) and are assembled by the caller
 * (HubSpotFiscalSyncService) directly from the Lead entity, which already carries them.
 */

/** Stable internal-name prefix for every custom property this integration owns. Never reuse this
 * prefix for anything unrelated to the fiscal calculator snapshot. */
export const HUBSPOT_FISCAL_PROPERTY_PREFIX = "bc_fiscal_";

export interface HubSpotFiscalScoreInput {
  score: number;
  scoreClass: FiscalScoreClass;
  version: string;
}

export interface HubSpotFiscalAttributionInput {
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  utm_content?: string;
  utm_term?: string;
  fbclid?: string;
  landing_page?: string;
  referrer?: string;
}

export interface HubSpotFiscalPropertiesInput {
  /** Same shape formatFiscalCalculatorNote takes, minus submissionId/submittedAt (passed
   * separately below, since they're also used outside the "note" concept here). */
  fiscalCalculator: Omit<FiscalCalculatorNoteInput, "submissionId" | "submittedAt">;
  submissionId: string;
  /**
   * Fase 6F.1 -- the AUTHORITATIVE moment this submission was captured by Lead Engine (the same
   * `submittedAt` app.ts's POST /api/leads handler already generates once per request and reuses
   * for `privacyAcceptedAt`/the leads.notes fiscal block -- see the Fase 6F.1 report, item 2).
   * NEVER the moment HubSpot happened to be reached -- that's `syncedAt`, below. impuestos.html's
   * calculator engine does not stamp its own "calculated at" timestamp anywhere, so this is the
   * closest authoritative substitute, documented explicitly per the task's instruction.
   */
  calculatedAt: Date;
  /**
   * Fase 6F.1 -- the moment THIS process actually attempted the HubSpot upsert. Always freshly
   * generated by HubSpotFiscalSyncService right before calling the provider -- never reused across
   * retries, never confused with `calculatedAt` above (see bc_fiscal_synced_at's doc comment on
   * the property-name list below for why both are kept as separate properties).
   */
  syncedAt: Date;
  /**
   * Fase 6F.1 -- audited: NO version tag exists anywhere in the calculator engine itself
   * (impuestos.html's calcular()/tasaEstimada() carry no version constant, and the frontend has
   * never sent one). Rather than silently inventing a plausible-looking version number for the
   * math engine (Fase 6F's original PPR_CALCULATOR_DEFAULT_VERSION = "ppr_calc_2026_v1" did
   * exactly that, and is corrected here), the caller must pass an EXPLICIT value: either whatever
   * impuestos.html sends (once it's ever updated to), or the honest placeholder
   * CALCULATION_VERSION_UNKNOWN, below -- never fiscal_v1 (that is bc_fiscal_score_version's
   * value, the SCORING formula's version, a completely different thing -- see the Fase 6F.1
   * report, item 3, and the dedicated test asserting the two are never equal for the same
   * submission).
   */
  calculationVersion: string;
  fiscalScore: HubSpotFiscalScoreInput;
  attribution?: HubSpotFiscalAttributionInput;
  source?: string;
  privacyAccepted: boolean;
  privacyAcceptedAt: Date;
  consentContact: boolean;
}

/**
 * Fase 6F.1 -- honest placeholder for `calculationVersion` when the caller (today, always -- see
 * the doc comment above) has no real engine-version tag to send. Deliberately NOT a fabricated
 * version string, and deliberately NOT `fiscal_v1` (that would conflate the calculation engine's
 * version with the scoring formula's version -- exactly the confusion this task's item 3 warns
 * against). If a genuinely versioned calculator engine ships later, that real version flows
 * through unchanged and this constant is simply never used for those submissions.
 */
export const CALCULATION_VERSION_UNKNOWN = "unknown";

function sumDeductions(d: { medicalExpenses: number; tuition: number; mortgageInterest: number; other: number }): number {
  return d.medicalExpenses + d.tuition + d.mortgageInterest + d.other;
}

/** Every HubSpot property this function CAN produce (used by tests/documentation to assert the
 * mapping table stays complete). Identification (firstname/lastname/email/phone) and native
 * city/state are intentionally absent -- see the module doc comment. */
export const HUBSPOT_FISCAL_PROPERTY_NAMES = [
  "bc_fiscal_age",
  "bc_fiscal_tax_regime",
  "bc_fiscal_files_annual_return",
  "bc_fiscal_monthly_income",
  "bc_fiscal_annual_income",
  "bc_fiscal_annual_ppr_contribution",
  // Fase 6F.1: the 4 exact deduction inputs (impuestos.html's p-medicos/p-colegiaturas/
  // p-hipoteca/p-otros -- see the Fase 6F.1 report, item 1), ADDED alongside (never replacing)
  // the pre-existing total below.
  "bc_fiscal_deduction_medical_expenses",
  "bc_fiscal_deduction_tuition",
  "bc_fiscal_deduction_mortgage_interest",
  "bc_fiscal_deduction_other",
  "bc_fiscal_personal_deductions", // total of the 4 above -- kept for a quick-glance view
  "bc_fiscal_has_ppr",
  "bc_fiscal_has_gmm",
  // Fase 6F.1: the calculator's own intermediate/capped values -- without these, the exact
  // estimate range cannot be reconstructed from HubSpot alone (see the Fase 6F.1 report, item 5).
  "bc_fiscal_ppr_deduction_limit",
  "bc_fiscal_effective_ppr_contribution",
  "bc_fiscal_other_deductions_considered",
  "bc_fiscal_estimate_min",
  "bc_fiscal_estimate_max",
  "bc_fiscal_submission_id",
  "bc_fiscal_calculated_at",
  "bc_fiscal_synced_at", // Fase 6F.1
  "bc_fiscal_calculation_version",
  "bc_fiscal_score",
  "bc_fiscal_score_class",
  "bc_fiscal_score_version",
  "bc_fiscal_source",
  "bc_fiscal_privacy_accepted",
  "bc_fiscal_privacy_accepted_at",
  "bc_fiscal_consent_contact",
  "bc_fiscal_utm_source",
  "bc_fiscal_utm_medium",
  "bc_fiscal_utm_campaign",
  "bc_fiscal_utm_content",
  "bc_fiscal_utm_term",
  "bc_fiscal_fbclid",
  "bc_fiscal_landing_page",
  "bc_fiscal_referrer",
] as const;

/**
 * Builds the flat `properties` object for a HubSpot Contact upsert from one fiscal calculator
 * submission. Never throws -- every field is either present in `input` (schema-guaranteed by
 * app.ts's fiscalCalculatorSchema) or optional and simply omitted when absent, never fabricated.
 *
 * FORBIDDEN by design (see the Fase 6F report's analytics-firewall / privacy sections): this
 * function's OUTPUT is exactly what leaves this process for HubSpot -- it never receives, and
 * therefore can never leak, a HubSpot API token, a raw HTTP response, or anything beyond the
 * fiscal snapshot fields listed in HUBSPOT_FISCAL_PROPERTY_NAMES above.
 */
export function buildHubSpotFiscalProperties(input: HubSpotFiscalPropertiesInput): Record<string, string | number | boolean> {
  const fc = input.fiscalCalculator;
  const d = fc.deductions;
  const properties: Record<string, string | number | boolean> = {
    bc_fiscal_files_annual_return: fc.filesAnnualReturn ?? false,
    bc_fiscal_monthly_income: fc.monthlyIncome,
    bc_fiscal_annual_income: fc.calculation.annualIncome,
    bc_fiscal_annual_ppr_contribution: fc.annualContribution,
    // Fase 6F.1: exact individual inputs -- never derived, never recalculated, verbatim from the
    // SAME `deductions` object formatFiscalCalculatorNote already receives.
    bc_fiscal_deduction_medical_expenses: d.medicalExpenses,
    bc_fiscal_deduction_tuition: d.tuition,
    bc_fiscal_deduction_mortgage_interest: d.mortgageInterest,
    bc_fiscal_deduction_other: d.other,
    bc_fiscal_personal_deductions: sumDeductions(d),
    bc_fiscal_has_ppr: fc.hasPpr ?? false,
    bc_fiscal_has_gmm: fc.hasGmm ?? false,
    // Fase 6F.1: intermediate/capped values from the calculator engine's own output -- transported
    // verbatim, never recomputed here (see the module doc comment and the Fase 6F.1 report item 6).
    bc_fiscal_ppr_deduction_limit: fc.calculation.pprDeductionLimit,
    bc_fiscal_effective_ppr_contribution: fc.calculation.effectivePprContribution,
    bc_fiscal_other_deductions_considered: fc.calculation.otherDeductionsConsidered,
    bc_fiscal_estimate_min: fc.calculation.estimatedTaxBenefitMin,
    bc_fiscal_estimate_max: fc.calculation.estimatedTaxBenefitMax,
    bc_fiscal_submission_id: input.submissionId,
    bc_fiscal_calculated_at: input.calculatedAt.toISOString(),
    bc_fiscal_synced_at: input.syncedAt.toISOString(),
    bc_fiscal_calculation_version: input.calculationVersion,
    bc_fiscal_score: input.fiscalScore.score,
    bc_fiscal_score_class: input.fiscalScore.scoreClass,
    bc_fiscal_score_version: input.fiscalScore.version,
    bc_fiscal_privacy_accepted: input.privacyAccepted,
    bc_fiscal_privacy_accepted_at: input.privacyAcceptedAt.toISOString(),
    bc_fiscal_consent_contact: input.consentContact,
  };
  if (fc.age !== undefined) properties.bc_fiscal_age = fc.age;
  if (fc.taxRegime) properties.bc_fiscal_tax_regime = fc.taxRegime;
  if (input.source) properties.bc_fiscal_source = input.source;

  const a = input.attribution;
  if (a?.utm_source) properties.bc_fiscal_utm_source = a.utm_source;
  if (a?.utm_medium) properties.bc_fiscal_utm_medium = a.utm_medium;
  if (a?.utm_campaign) properties.bc_fiscal_utm_campaign = a.utm_campaign;
  if (a?.utm_content) properties.bc_fiscal_utm_content = a.utm_content;
  if (a?.utm_term) properties.bc_fiscal_utm_term = a.utm_term;
  if (a?.fbclid) properties.bc_fiscal_fbclid = a.fbclid;
  if (a?.landing_page) properties.bc_fiscal_landing_page = a.landing_page;
  if (a?.referrer) properties.bc_fiscal_referrer = a.referrer;

  return properties;
}
