/**
 * Row-per-conversation ownership claim protecting SlotOfferingService's "create a new round"
 * critical section (check active offer -> check round count -> Calendar -> createMany ->
 * transition) against two concurrent callers both creating a round for the same conversation.
 * Lives in Postgres (migration 011) so the exclusion holds across multiple app instances, not
 * just within one process. See slot-offering-service.ts for the full ownership protocol.
 */
export interface SlotOfferClaim {
  conversationId: string;
  /** Identifies the current owner. Part of the CAS predicate for both stale-reclaim and
   * release -- an owner who lost the claim (reclaimed by someone else) can never release or
   * mutate it again, because its own ownerToken no longer matches. */
  ownerToken: string;
  /** Generated by the owner BEFORE persisting anything, and used verbatim as the round_id for
   * every offered_slots row that owner creates -- never re-generated inside the persist step.
   * Lets a stuck/orphaned claim be reconciled unambiguously against offered_slots if needed. */
  intendedRoundId: string;
  claimedAt: Date;
  updatedAt: Date;
}
