import type { LeadStatus } from "./lead.js";
import { InvalidLeadTransitionError } from "./errors.js";
const transitions: Record<LeadStatus, readonly LeadStatus[]> = {
  NEW:["CONTACT_PENDING","CONTACTED","DO_NOT_CONTACT","HUMAN_HANDOFF"],
  CONTACT_PENDING:["CONTACTED","DO_NOT_CONTACT","HUMAN_HANDOFF"],
  CONTACTED:["QUALIFYING","DO_NOT_CONTACT","HUMAN_HANDOFF"],
  QUALIFYING:["QUALIFIED_A","QUALIFIED_B","NURTURE_C","DO_NOT_CONTACT","HUMAN_HANDOFF"],
  QUALIFIED_A:["BOOKING_PENDING","BOOKED","DO_NOT_CONTACT","HUMAN_HANDOFF"],
  QUALIFIED_B:["BOOKING_PENDING","NURTURE_C","BOOKED","DO_NOT_CONTACT","HUMAN_HANDOFF"],
  NURTURE_C:["QUALIFYING","DO_NOT_CONTACT","HUMAN_HANDOFF"],
  BOOKING_PENDING:["BOOKED","NURTURE_C","DO_NOT_CONTACT","HUMAN_HANDOFF"],
  BOOKED:["CONFIRMED","RESCHEDULE_REQUESTED","NO_SHOW","MEETING_COMPLETED","DO_NOT_CONTACT"],
  CONFIRMED:["RESCHEDULE_REQUESTED","NO_SHOW","MEETING_COMPLETED","DO_NOT_CONTACT"],
  RESCHEDULE_REQUESTED:["BOOKED","DO_NOT_CONTACT"],
  NO_SHOW:["BOOKING_PENDING","BOOKED","CLOSED_LOST","DO_NOT_CONTACT"],
  MEETING_COMPLETED:["QUOTE_PENDING","QUOTE_SENT","CLOSED_WON","CLOSED_LOST"],
  QUOTE_PENDING:["QUOTE_SENT","CLOSED_WON","CLOSED_LOST"],
  QUOTE_SENT:["CLOSED_WON","CLOSED_LOST"],
  CLOSED_WON:[], CLOSED_LOST:[], DO_NOT_CONTACT:[],
  HUMAN_HANDOFF:["CONTACTED","QUALIFYING","BOOKING_PENDING","DO_NOT_CONTACT"]
};
export const canTransition=(from:LeadStatus,to:LeadStatus)=>transitions[from].includes(to);
export function assertTransition(from:LeadStatus,to:LeadStatus){if(!canTransition(from,to)) throw new InvalidLeadTransitionError(from,to);}
